### ISSUE TITLE
Best way to get the retrieve the window handle (hWnd)?

### ISSUE THREAD

**Issue by DiagProf** [AndrewKeepCoding/WinUI3AppProjectTemplatesExtension#5]
Thanks for the very nice extenstion. I like very much.
But now I've come to a place where I'm not sure how to do it.
For WinUI 3 and Desktop I need e.g. File FileOpenPicker a hWnd.
But on a page not on the main window. (therefore it does not work as it is described here https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/retrieve-hwnd) 
How would you extend your extension to get access? As a service?

**Comment by AndrewKeepCoding** [comment]
Thanks for using the extension!

Of course creating a service is one way to do it. But the way to initialize the ``FileOpenPicker`` is kind of tricky and I'm sure that the WinUI 3 team will improve this. So I wouldn't go too far and just do it like this (for the moment):

**App.xaml.cs**
```csharp
using Microsoft.UI.Xaml;

namespace WinUI3BlankAppProjectTemplate;

public partial class App : Application
{
    public static MainWindow MainWindow { get; } = new();

    public App()
    {
        this.InitializeComponent();
    }

    protected override void OnLaunched(LaunchActivatedEventArgs args)
    {
        MainWindow.Activate();
    }
}
```

**MainWindow.xaml.cs**
```csharp
using Microsoft.UI.Xaml;
using System;
using WinRT.Interop;

namespace WinUI3BlankAppProjectTemplate;

public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
    }

    public void InitializeWithWindow(object target)
    {
        IntPtr handle = WindowNative.GetWindowHandle(this);
        WinRT.Interop.InitializeWithWindow.Initialize(target, handle);
    }
}
```

**MainPage.xaml.cs**
```csharp
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System;
using Windows.Storage;
using Windows.Storage.Pickers;

namespace WinUI3BlankAppProjectTemplate;

public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this.InitializeComponent();
    }

    private async void Button_Click(object sender, RoutedEventArgs e)
    {
        FileOpenPicker picker = new();
        App.MainWindow.InitializeWithWindow(picker);
        StorageFile file = await picker.PickSingleFileAsync();
    }
}
```

**Comment by DiagProf** [comment]
Thank you for this detailed explanation.  
I also thought that service might not be such a good idea.

I had something like that in mind


`
using WinRT.Interop;
public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this.InitializeComponent();
    }

    private async void Button_Click(object sender, RoutedEventArgs e)
    {
        FileOpenPicker picker = new();
        //var hwnd = Process.GetCurrentProcess().MainWindowHandle; //the hard solution to get the handle
        //or
        var hwnd = Ioc.Default.GetRequiredService<MainWindow>();
         WinRT.Interop.InitializeWithWindow.Initialize(picker, hwnd);
        StorageFile file = await picker.PickSingleFileAsync();
    }
}`

But your solution is much more elegant!!! Thanks for that.

By the way, what else I thought was cool for the extension. That if you are in the settings you can save the window size to which you dragged the window with the mouse (in principle the current height and width)

**Comment by AndrewKeepCoding** [comment]
I just published 4 Visual Studio extensions corresponding to each project template. Now we can install only the project templates we need. It includes the change you requested. Hope it helps.

I also marked the old single extension as deprecated. So please switch to the new ones.

**Comment by DiagProf** [comment]
I checked it out. The commented out is how it works from you. The new code is what I had in mind. And that's how it works for me. I'm not sure if you really wanted to reload the data from the store (LoadWindowSizeSettings).

`        [RelayCommand]
        private void LoadWindowSize()
        {
            if (_windowingService.GetWindowSize() is (int, int) windowSize)
            {
                WindowWidth = windowSize.Width;
                WindowHeight = windowSize.Height;
                _ = _windowingService.SaveWindowSizeSettings(WindowWidth, WindowHeight);
            }
           
            //if (_windowingService.LoadWindowSizeSettings() is (int, int) windowSize)
            //{
            //    _windowingService.SetWindowSize(windowSize.Width, windowSize.Height);
            //}
        }`
